WEEWX_ROOT = .
USER_ROOT = bin/user

[Station]
    station_type = Simulator
    latitude = 52.52
    longitude = 13.405
    altitude = 40, meter

[Simulator]
    driver = weewx.drivers.simulator
    mode = simulator
    loop_interval = 2.5
    observations = outTemp, outHumidity, rain, windSpeed, windDir, windGust, windGustDir
