WEEWX_ROOT = .
USER_ROOT = bin/user

[Station]
    station_type = Simulator
    latitude = 52.52
    longitude = 13.405
    altitude = 50, meter

[Simulator]
    driver = weewx.drivers.simulator
    mode = simulator
    loop_interval = 5
    observations = outTemp, rain, windSpeed, windDir
