WEEWX_ROOT = .
USER_ROOT = bin/user

[Station]
    station_type = Vantage
    latitude = 52.52
    longitude = 13.405
    altitude = 40, meter

[Vantage]
    driver = weewx.drivers.vantage
    type = serial
    port = /dev/serial/by-id/REPLACE_WITH_CONSOLE
    baudrate = 19200
